### ISSUE TITLE
matches.tuple typed as Validator<unknown, never>

### ISSUE THREAD

**Issue by speigg** [Blu-J/ts-matches#473]
I'm seeing this bug:

```ts
matches.tuple([matches.number, matches.number, matches.number]) 
// expected type: Validator<unknown, [number,number,number]>
// actual type: Validator<unknown, never>
```

I'm seeing `Validator<unknown, never>` for all matches.tuple types

**Comment by Blu-J** [comment]
Yes, it should be exactly the output, I have a test for this, will go about creating a fix. Thanks for finding, I think I have a unit test that will stop the regression, will work on it. 
```ts

      it("should be able to check tuple exact shape", () => {
        const input = [1, 2, 3];
        const matcher = matches.tuple([
          matches.number,
          matches.number,
          matches.number,
        ]);
        // @ts-expect-error
        const outputWrong: [number, number] = matcher.unsafeCast(input);
        const outputRight: [number, number, number] = matcher.unsafeCast(input);
        // expected type: Validator<unknown, [number,number,number]>
        // actual type: Validator<unknown, never>;
        expect(outputRight).toEqual(input);
        expect(outputWrong).toEqual(input);
      });
   ```
   This will hit master, but there are new features so going to be a new version. What version would you also like for me to backprop this to?

**Comment by speigg** [comment]
A new version is fine! This is a great library, thanks for creating it!

**Comment by Blu-J** [comment]
Had to change the api for the creation of the tuples because of the ability to infer and tuples

**Comment by speigg** [comment]
Seems like a nicer API this way anyway, thanks for the fix!
