### ISSUE TITLE
Transpile to esmodule format? 

### ISSUE THREAD

**Issue by speigg** [Blu-J/ts-matches#481]
Our build/bundle toolchain (using vite and esbuild) is somehow breaking ts-matches; 

```
TypeError: t.Parser is not a constructor
    at SimpleParsers.js:23
    at SimpleParsers.js:38
```

The only way I could manage to get our build to work was by including the ts-matches source code in our repo ( https://github.com/XRFoundation/XREngine ). I think we  would have less problems bundling ts-matches from node_modules if the library was transpiled into esmodule format rather than (or in addition to) commonjs.

**Comment by Blu-J** [comment]
I'v wanted to get into the esmodule. Would still love to have the common js, but if that's not possible, then major version I guess.
Could you create a PR since you sound more familiar with this?

**Comment by Blu-J** [comment]
Yeah, let me know.

**Comment by Blu-J** [comment]
Well, I wish I could test and fix this

**Comment by speigg** [comment]
I looked at this again; I think I had failed to `npm install` w/ the new version number last time. Nevertheless, there is still a major problem w/ the `feat--esm-builds` branch. 

It looks like the main/module/exports are completely wrong:
```json
  "main": "lib/cjs/index.js",
  "module": "lib/mjs/index.js",
  "exports": {
    ".": {
      "import": "./lib/mjs/index.js",
      "require": "./lib/cjs/index.js"
    }
  },
  ```
should be:
```json
  "main": "lib/cjs/matches.js",
  "module": "lib/mjs/matches.js",
  "exports": {
    ".": {
      "import": "./lib/mjs/matches.js",
      "require": "./lib/cjs/matches.js"
    }
  },
  ```

**Comment by Blu-J** [comment]
ts-matches@5.1.0-1 Should be out, hopefully this works, sorry for being slow

**Comment by speigg** [comment]
Thank you! Works properly in our deployment build now!
